# Generated by Django 5.1.6 on 2025-03-14 13:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero_section', 3), ('palace_language_section', 8), ('about_us_section', 9), ('add_ons_section', 12), ('testimonials_section', 14), ('trusted_by_brands_section', 16)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('heading', 1), ('subheading', 2)]], {}), 4: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'FontAwesome icon class or similar', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('icon', 5), ('title', 1), ('text', 2)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('title', 1), ('description', 4), ('features', 7)]], {}), 9: ('wagtail.blocks.StructBlock', [[('title', 1), ('description', 4)]], {}), 10: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL of image or video', 'required': True}), 11: ('wagtail.blocks.StructBlock', [[('image_or_video', 10), ('title', 1), ('text', 2)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('name', 1), ('quote', 2)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('logo', 0), ('name', 1)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {})}, default=[]),
        ),
    ]
